# Generated by Django 4.1.7 on 2023-05-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_fridge_comment_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='fridge',
        ),
    ]
