# Generated by Django 4.1.7 on 2023-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_comment_comment_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
