# Generated by Django 4.1.7 on 2023-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
