# Generated by Django 4.1.7 on 2023-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_comment_fridgecomment_fridge_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='antibacterial_coating',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Антибактериальное покрытие'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='autonomous_cold_storage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автономное сохранение холода'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='child_protection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Защита от детей'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='climate_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Климатический класс'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='coating_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал покрытия'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='control_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип управления'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='count_coolstore',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество камер'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='guarantee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='holiday_mode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Режим "Отпуск"'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='ice_maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Генератор льда'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='inverter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инверторный'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Изготовитель'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='open_door_indicator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индикация открытой двери'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='package_length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина упаковки'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='peculiarities',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='power_failure_indicator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индикация отключения электропитания'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='shelf_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал полок'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='temperature_increase_indicator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индикация повышения температуры'),
        ),
    ]
