# Generated by Django 4.1.7 on 2023-05-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fridge_antibacterial_coating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeGrade',
            fields=[
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('total_grade', models.IntegerField(default=0)),
                ('fridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.fridge')),
            ],
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='grade',
        ),
    ]
