# Generated by Django 4.1.7 on 2023-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mobilephone_mobilephonegrade_mobilephonecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='total_useful_volume',
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Емкость аккумулятора'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стандарт Bluetooth'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='builtin_memory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Объем встроенной памяти'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='calculator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Калькулятор'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фотокамера'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='camera_resolution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Разрешение фотокамеры'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='computer_synchronization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Синхронизация с компьютером'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='front_camera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='gsm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GSM'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='guarantee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='headphone_output',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выход на наушники'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Изготовитель'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='max_memory_card_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальный объем карты памяти'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='memory_card_slot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слот для карты памяти'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='memory_card_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип карты памяти'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='organizer_calendar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Органайзер/календарь'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='peculiarities',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Объем встроенной памяти'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='screen_diagonal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Диагональ экрана'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='screen_matrix_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип матрицы экрана'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='sos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наличие кнопки SOS'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='talk_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время разговора'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Толщина'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='three_g_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Поддержка 3G (UMTS)'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='touch_screen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сенсорный экран'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='usb_interface',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Интерфейс USB'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='wi_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ширина'),
        ),
    ]
