# Generated by Django 4.1.7 on 2023-05-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mobilephone_total_useful_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multicooker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='Ссылка на картинку')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('bowl_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Объем чаши')),
                ('control_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип управления')),
                ('three_d_heating', models.CharField(blank=True, max_length=100, null=True, verbose_name='3D нагрев')),
                ('housing_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал корпуса')),
                ('bowl_cover', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покрытие чаши')),
                ('power_consumption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Потребляемая мощность')),
                ('delayed_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отложенный старт')),
                ('max_timer_setting_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальное время установки таймера')),
                ('keep_warm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Поддержание тепла')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('guarantee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия')),
                ('viewing_window', models.CharField(blank=True, max_length=100, null=True, verbose_name='Смотровое окно')),
                ('count_automatic_program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Число автоматических программ')),
            ],
            options={
                'verbose_name': 'Мультиварка',
                'verbose_name_plural': 'Мультиварки',
            },
        ),
        migrations.CreateModel(
            name='MulticookerGrade',
            fields=[
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('total_grade', models.IntegerField(default=0)),
                ('multicooker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.multicooker')),
            ],
        ),
        migrations.CreateModel(
            name='MulticookerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('grade', models.IntegerField(null=True)),
                ('multicooker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.multicooker')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
